### ISSUE TITLE
Небольшая опечатка в статье

### ISSUE THREAD

**Issue by Futsey** [hipravin/samples-algorithm-complexity#1]
Здравствуйте! Огромное спасибо Вам за очень подробные и полезные статьи!
Как бы не желал быть граммар-нацци, но на общем фоне великолепного оформления небольшая оплошность в тексте немного портит впечатление. Статья "Алгоритмическая сложность"
![image](https://user-images.githubusercontent.com/89212538/220279927-eba66f29-4b30-4b56-801c-fdbf449f0906.png)

**Comment by hipravin** [comment]
Благодарю за обратную связь!
Исправил и заодно добавил несколько комментариев в данную статью.
